# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallForAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(default=b'Synopsis', max_length=300)),
                ('action_location', models.CharField(default=b'Erehwon', max_length=30)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contributors', models.CharField(default=b'Erehwon', max_length=20)),
                ('call_label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ErehwonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=300)),
                ('label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=300)),
                ('material', models.URLField(blank=True, max_length=300)),
                ('active_status', models.BooleanField(default=1)),
                ('is_added_to_map', models.BooleanField(default=0)),
                ('label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ErehwonUser')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Project'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ErehwonUser'),
        ),
        migrations.AddField(
            model_name='callforaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ErehwonUser'),
        ),
    ]
