# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErehwonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='CallForAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(default=b'Synopsis', max_length=300)),
                ('action_location', models.CharField(default=b'Erehwon', max_length=30)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contributors', models.CharField(default=b'Erehwon', max_length=20)),
                ('call_label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=300)),
                ('label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=300)),
                ('material', models.URLField(blank=True, max_length=300)),
                ('active_status', models.BooleanField(default=1)),
                ('is_added_to_map', models.BooleanField(default=0)),
                ('label', models.CharField(choices=[(b'A', b'Activism'), (b'DA', b'Digital Activism'), (b'CD', b'Community Development'), (b'UP', b'Urban Planning'), (b'NE', b'New Ecologies'), (b'AE', b'Alternative Economies'), (b'CM', b'Citizen Movement'), (b'AI', b'Artistic Interventions')], default=b'A', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Project'),
        ),
    ]
