# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callforaction',
            name='call_label',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='label',
        ),
        migrations.RemoveField(
            model_name='project',
            name='label',
        ),
        migrations.AlterField(
            model_name='project',
            name='material',
            field=models.FileField(upload_to=b'MEDIA_ROOT'),
        ),
    ]
