# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.CharField(default=b'username', max_length=20),
        ),
    ]
