# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_callforaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callforaction',
            old_name='idea_title',
            new_name='call_title',
        ),
        migrations.RemoveField(
            model_name='callforaction',
            name='idea_synopsis',
        ),
    ]
