# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160530_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforaction',
            name='synopsis',
            field=models.TextField(default=b'Synopsis', max_length=300),
        ),
    ]
