# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_idea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callforaction',
            name='call_label',
        ),
        migrations.AddField(
            model_name='callforaction',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
