# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170521_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='label',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='label',
        ),
    ]
