# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_callforaction_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforaction',
            name='action_location',
            field=models.CharField(default=b'Erehwon', max_length=30),
        ),
        migrations.AddField(
            model_name='callforaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
