# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170522_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='contributors',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
