# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_callforaction_call_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callforaction',
            name='contributors',
        ),
    ]
