# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160728_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforaction',
            name='contributors',
            field=models.CharField(default=b'Erehwon', max_length=20),
        ),
    ]
